#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, stage by stage.
# Generated by the `wizard` skill.
#
# Copy the library above the "STAGES" marker unchanged into generated wizards.
# Author the stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# Colour only on a terminal that advertises the 8 basic ANSI colours
# (tput setaf 0-7); otherwise every style variable is empty.
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current stage is on screen. No-op when
# output isn't a terminal, so piped logs stay readable. Without tput it falls
# back to raw ANSI: 2J clears the screen, 3J the scrollback, H homes the cursor.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Ctrl-C stops the wizard. Re-running\n'
  printf '  starts from stage 1 and offers saved .env values as defaults.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a bulleted action the human takes in the browser.
# note "..." is dim context; warn "..." is a yellow warning.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  local opener
  for opener in wslview explorer.exe xdg-open open; do
    if command -v "$opener" >/dev/null 2>&1; then
      "$opener" "$url" >/dev/null 2>&1 && return 0
      break
    fi
  done
  warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || { warn "Input closed; stopped at the current stage"; exit 1; }
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || { warn "Input closed; value not saved"; exit 1; }
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || { printf '\n'; warn "Input closed; value not saved"; exit 1; }
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per entry in the stage list.

TOTAL_STAGES=4

banner "Linux live lifecycle verification"

stage "Linux host prerequisites"
open_url "https://github.com/grauzone-dev/sandboxed-agents/blob/main/docs/host-prerequisites.md"
say "This wizard needs Linux amd64, Go 1.27 or newer, git, and Podman 4.4.0 or newer set up as on the opened page, in a clean checkout at the repository root. It builds the executable and runs its host check next; if any step fails, the wizard stops before any sandbox exists."
[[ "$(uname -s)" == Linux && "$(uname -m)" == x86_64 ]] || { warn "This wizard runs only on Linux amd64. On Windows 11, use the PowerShell command from docs/live-suite.md instead."; exit 1; }
git rev-parse --show-toplevel >/dev/null
[[ "$PWD" == "$(git rev-parse --show-toplevel)" ]] || { warn "Run this wizard from the repository root: bash scripts/live-lifecycle-wizard.sh"; exit 1; }
go version
podman --version
go run ./tools/build
.scratch/sandboxed-agents check
pause "The host check passed. Press Enter to continue to the lifecycle run"

stage "Linux lifecycle run"
say "The live suite now runs the lifecycle part against real Podman in a new, empty controller group. It creates one sandbox, takes it through stop, start, remove, and an adopting up, and observes its isolation. It deletes only what this run created, never with --force: the sandbox, its three volumes, and its temporary observation containers. It issues no build; up builds the base image only if it is missing. Keep the console output to yourself. If the run fails, its cleanup still tries to remove the sandbox, the wizard stops, and the failing summary stays in .scratch/live."
confirm "Run the lifecycle part now?" || { warn "Stopped before the lifecycle run; nothing was created"; exit 1; }
live_group="live-lifecycle-$(date -u +%Y%m%d%H%M%S)-$$"
SANDBOXED_AGENTS_GROUP="$live_group" go run ./tools/live -opt-in -lifecycle -output .scratch/live
pause "The Linux run passed. Press Enter to continue"

stage "Windows follow-up"
open_url "https://github.com/grauzone-dev/sandboxed-agents/issues/24"
say "Windows 11 stays pending: this wizard does not run it, and no Windows result exists until the suite passes on a Windows 11 host. Run it later in PowerShell from the repository root of a clean checkout of the same commit:"
step '$env:SANDBOXED_AGENTS_GROUP = "live-lifecycle-" + (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss"); go run ./tools/live -opt-in -lifecycle'
pause "Press Enter once you have noted the Windows command for later"

stage "Results and cleanup"
say "The redacted Linux summary of this run:"
cat .scratch/live/live-suite-linux.json
say "To share the result, copy only this JSON into the conversation. The wizard posts and uploads nothing."
note "This summary validates no release: image_coverage_complete stays false and Windows 11 is pending. The run deleted only what it created; the base image that it built or reused stays on the host."
pause "Press Enter to finish"

finish
